services:
  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ~/jupyter-devops-data/work:/home/jovyan/work
      - ~/.aws:/home/jovyan/.aws:ro
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=askbianca
      - AWS_PROFILE=default
      - AWS_REGION=us-east-1
    restart: unless-stopped
